Regenerated
git-svn-id: http://svn.zoneminder.com/svn/zm/trunk@3146 e3e1d417-86f3-4887-817a-d78f3d33393f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8083,6 +8083,83 @@ echo "$as_me: WARNING: libavutil.a may be required for MPEG streaming" >&2;}
 fi
 
 
+echo "$as_me:$LINENO: checking for av_image_copy in -lavcore" >&5
+echo $ECHO_N "checking for av_image_copy in -lavcore... $ECHO_C" >&6
+if test "${ac_cv_lib_avcore_av_image_copy+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lavcore  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char av_image_copy ();
+int
+main ()
+{
+av_image_copy ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_avcore_av_image_copy=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_avcore_av_image_copy=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_avcore_av_image_copy" >&5
+echo "${ECHO_T}$ac_cv_lib_avcore_av_image_copy" >&6
+if test $ac_cv_lib_avcore_av_image_copy = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBAVCORE 1
+_ACEOF
+
+  LIBS="-lavcore $LIBS"
+
+else
+  { echo "$as_me:$LINENO: WARNING: libavcore.a may be required for MPEG streaming" >&5
+echo "$as_me: WARNING: libavcore.a may be required for MPEG streaming" >&2;}
+fi
+
+
 echo "$as_me:$LINENO: checking for avcodec_init in -lavcodec" >&5
 echo $ECHO_N "checking for avcodec_init in -lavcodec... $ECHO_C" >&6
 if test "${ac_cv_lib_avcodec_avcodec_init+set}" = set; then
