Added warning to run zmconfig.pl
git-svn-id: http://svn.zoneminder.com/svn/zm/trunk@369 e3e1d417-86f3-4887-817a-d78f3d33393f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2095,3 +2095,29 @@ chmod +x $CONFIG_STATUS
 rm -fr confdefs* $ac_clean_files
 test "$no_create" = yes || ${CONFIG_SHELL-/bin/sh} $CONFIG_STATUS || exit 1
 
+
+
+ac_safe=`echo "zmconfig.txt" | sed 'y%./+-%__p_%'`
+echo $ac_n "checking for zmconfig.txt""... $ac_c" 1>&6
+echo "configure:2103: checking for zmconfig.txt" >&5
+if eval "test \"`echo '$''{'ac_cv_file_$ac_safe'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test "$cross_compiling" = yes; then
+    { echo "configure: error: Cannot check for file existence when cross compiling" 1>&2; exit 1; }
+else
+  if test -r zmconfig.txt; then
+    eval "ac_cv_file_$ac_safe=yes"
+  else
+    eval "ac_cv_file_$ac_safe=no"
+  fi
+fi
+fi
+if eval "test \"`echo '$ac_cv_file_'$ac_safe`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+  :
+else
+  echo "$ac_t""no" 1>&6
+echo "configure: warning: Now run 'perl zmconfig.pl' to create your ZoneMinder configuration" 1>&2
+fi
+
