Move call to zmupdate.pl in core package because it requires zm.conf file and perl libraries

diff --git a/distros/debian8/zoneminder-core.postinst b/distros/debian8/zoneminder-core.postinst
--- a/distros/debian8/zoneminder-core.postinst
+++ b/distros/debian8/zoneminder-core.postinst
@@ -63,6 +63,18 @@ if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ]; then
     chmod 640 $CONFIGFILE
 fi
 
+# Do this every time the package is installed or upgraded
+# Test for database presence to avoid failure of zmupdate.pl
+if [ "$dbc_install" = "true" ] && [ "$1" = "configure" ]; then
+
+    # Ensure zoneminder is stopped
+    deb-systemd-invoke stop zoneminder.service || exit $?
+
+    # Run the ZoneMinder update tool
+    zmupdate.pl
+
+fi
+
 #DEBHELPER#
 
 exit 0
